import Head from 'next/head'
import Home from './home'

export default function Index() {
  console.log(process.env.NEXT_PUBLIC_SUPABASE_KEY);
  return (
    <div>
      <Head>
        <title>Calories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
      
    </div>
  )
}
